// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcfvPytkokzZSW15UWymB_2LiF5dDsmdc',
    appId: '1:971362506361:web:9c90206b479cfae82526a8',
    messagingSenderId: '971362506361',
    projectId: 'novanest-chat-app',
    authDomain: 'novanest-chat-app.firebaseapp.com',
    storageBucket: 'novanest-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwa26jJEm1gW8rVbTHddJawcb9XrI6axQ',
    appId: '1:971362506361:android:6b0e598be8af36812526a8',
    messagingSenderId: '971362506361',
    projectId: 'novanest-chat-app',
    storageBucket: 'novanest-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWvk5a98Zw6JjYugzKkuPLNox3Yi8HlSA',
    appId: '1:971362506361:ios:412ab762cfe717b42526a8',
    messagingSenderId: '971362506361',
    projectId: 'novanest-chat-app',
    storageBucket: 'novanest-chat-app.appspot.com',
    androidClientId: '971362506361-u7q0205358l3getlhv3nun3gq9vsj2as.apps.googleusercontent.com',
    iosClientId: '971362506361-56bgm5iv2eja08bkpdhuoihc1du9rio7.apps.googleusercontent.com',
    iosBundleId: 'com.example.novanest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWvk5a98Zw6JjYugzKkuPLNox3Yi8HlSA',
    appId: '1:971362506361:ios:412ab762cfe717b42526a8',
    messagingSenderId: '971362506361',
    projectId: 'novanest-chat-app',
    storageBucket: 'novanest-chat-app.appspot.com',
    androidClientId: '971362506361-u7q0205358l3getlhv3nun3gq9vsj2as.apps.googleusercontent.com',
    iosClientId: '971362506361-56bgm5iv2eja08bkpdhuoihc1du9rio7.apps.googleusercontent.com',
    iosBundleId: 'com.example.novanest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcfvPytkokzZSW15UWymB_2LiF5dDsmdc',
    appId: '1:971362506361:web:8223572af9b660482526a8',
    messagingSenderId: '971362506361',
    projectId: 'novanest-chat-app',
    authDomain: 'novanest-chat-app.firebaseapp.com',
    storageBucket: 'novanest-chat-app.appspot.com',
  );

}